Remove Comparable requirement from Range bound
Fails due to

/Users/dave/src/hylo/Sources/IR/Emitter.swift:2321: Fatal error: lvalue lowering for cast expressions #1049